
name: Segundo Workflow

on:
    push:

jobs:

    segundo-job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v5
            - name: ler Readme
              run: cat README.md